#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013-2014 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

import json
import sys

import matplotlib.pyplot as pl
import numpy as np
import scipy.optimize as op
import scipy.misc
import scipy.interpolate
import unitprint

def gauss(x, mean, stddev, amplitude):
    return amplitude * np.exp(- ((x - mean) / stddev)**2)

def linear(x, a, b):
    return x * a + b

def exp_sec_deg(x, a, b, c, d):
    return a * np.exp(b * x) + c * np.exp(d * x)

def fit_peak(T, filename, lower, upper, p0, prefix, impuls, d_impuls, linie, show=False):
    data = np.loadtxt(filename)
    bins = data[:, 0]
    counts = data[:, 1]

    fit_bins = bins[lower:upper]
    fit_counts = counts[lower:upper]

    popt, pconv = op.curve_fit(gauss, fit_bins, fit_counts, p0=p0)
    d = np.sqrt(pconv.diagonal())
    x = np.linspace(np.min(fit_bins), np.max(fit_bins), 1000)
    y = gauss(x, *popt)

    T['{}_{}_mean_spannung'.format(prefix, linie)] = unitprint.siunitx(popt[0], d[0])
    T['{}_{}_std_spannung'.format(prefix, linie)] = unitprint.siunitx(popt[1], d[1])

    np.savetxt('_build/fit_{}_{}.txt'.format(prefix, linie), np.column_stack([x, y]))

    if show:
        pl.plot(bins, counts)
        pl.plot(fit_bins, fit_counts)
        pl.plot(x, y)
        pl.show()
    # (Schwerpunkt, Fehler, Standartabweichung, Fehler, Impuls, Fehler)
    return (popt[0], d[0], abs(popt[1]), d[1], impuls, d_impuls)

def fit_gauge_points(T, points, show=False):
    p = np.array(points)
    hall = p[:, 0]
    d_hall = p[:, 1]
    width_val = p[:, 2]
    width_err = p[:, 3]
    impuls = p[:, 4]
    d_impuls = p[:, 5]
    popt, pconv = op.curve_fit(linear, hall, impuls)
    d = np.sqrt(pconv.diagonal())

    points_table = np.column_stack([hall[1:], impuls[1:], d_hall[1:], d_impuls[1:]])
    np.savetxt('_build/impulseichung_data.txt', points_table)
    T['fit_impulseichung_data'] = list(zip(
        unitprint.siunitx(hall, d_hall),
        unitprint.siunitx(width_val, width_err),
        unitprint.siunitx(impuls),
    ))

    hall = hall[1:]
    x = np.linspace(np.min(hall)-2, np.max(hall)+1, 10)
    y = linear(x, *popt)

    T['fit_impulseichung_steigung'] = unitprint.siunitx(popt[0], d[0])
    T['fit_impulseichung_offset'] = unitprint.siunitx(popt[1], d[1])

    fit_table = np.column_stack([x, y])
    np.savetxt('_build/fit_impulseichung.txt', fit_table)

    return popt, pconv

def impulseichung(T):
    gauge_points = [(0,0,0,0,0,0)]

    # Energien der Konversionslinien berechnen
    m_e = 9.1e-31
    c = 3e8
    e = 1.6e-19
    gamma = 661.660
    T['energie_gamma'] = gamma
    K_bindung = 37.441
    T['energie_K_bindung'] = K_bindung
    L_bindung_1 = 5.987
    T['energie_L_bindung_1'] = L_bindung_1
    L_bindung_2 = 5.624
    T['energie_L_bindung_2'] = L_bindung_2
    L_bindung_3 = 5.247
    T['energie_L_bindung_3'] = L_bindung_3
    L_bindung = np.mean([L_bindung_1, L_bindung_2, L_bindung_3])
    dL_bindung = np.std([L_bindung_1, L_bindung_2, L_bindung_3])
    T['energie_L_bindung'] = unitprint.siunitx(L_bindung, dL_bindung)
    # Energien in Impulse mit natürlich Einheiten umrechnen
    K = np.sqrt(((gamma - K_bindung)*1e3*e/(m_e*c**2))**2-1)
    T['impuls_K_konversion'] = unitprint.siunitx(K)
    L = np.sqrt(((gamma - L_bindung)*1e3*e/(m_e*c**2))**2-1)
    dL = (gamma - L_bindung)*1e3*(e/(m_e*c**2))**2/L*dL_bindung
    T['impuls_L_konversion'] = unitprint.siunitx(L, dL)
    print(L_bindung)
    print(dL_bindung)
    print(L)
    print(dL)

    gauge_points.append(fit_peak(T, '_build/02_Cs_40s_bearb.txt', 12, 26, [155.8, 3, 5], 'konversion_40', K, 0, 'K'))
    gauge_points.append(fit_peak(T, '_build/02_Cs_40s_bearb.txt', 26, 35, [159.2, 4, 2], 'konversion_40', L, dL, 'L'))

    gauge_points.append(fit_peak(T, '_build/03_Cs_100s_bearb.txt', 14, 24, [157.8, 3, 6], 'konversion_100', K, 0, 'K'))
    gauge_points.append(fit_peak(T, '_build/03_Cs_100s_bearb.txt', 24, 34, [162, 4, 2], 'konversion_100', L, dL, 'L'))

    popt, pconv = fit_gauge_points(T, gauge_points)

    kurie(T, popt, pconv, '04_Tl', 80)
    kurie(T, popt, pconv, '05_Na', 200)

    # gauge_points: (Schwerpunkt, Fehler, Standartabweichung, Fehler, Impuls, Fehler)

    T['aufloesung_40s'] = []
    T['aufloesung_100s'] = []
    aufloesung(T['aufloesung_40s'], gauge_points[1][4], gauge_points[1][2], gauge_points[1][3], popt, pconv)
    aufloesung(T['aufloesung_40s'], gauge_points[2][4], gauge_points[2][2], gauge_points[2][3], popt, pconv)
    aufloesung(T['aufloesung_100s'], gauge_points[3][4], gauge_points[3][2], gauge_points[3][3], popt, pconv)
    aufloesung(T['aufloesung_100s'], gauge_points[4][4], gauge_points[4][2], gauge_points[4][3], popt, pconv)

def aufloesung(Tlist, value, width, dwidth, popt, pconv):
    sigma_val = popt[0]*width
    fwhm_val = sigma_val * 2 * np.sqrt(2 * np.log(2))

    sigma_err =  np.sqrt((width*pconv[0][0])**2 + (popt[0]*)**2)
    fwhm_err = sigma_err * 2 * np.sqrt(2 * np.log(2))

    Tlist.append([
        value,
        unitprint.siunitx(fwhm_val, fwhm_err),
        unitprint.siunitx(value/fwhm_val, value/fwhm_val**2 * fwhm_err),
    ])


def kurie(T, popt, pconv, basename, time):
    data = np.loadtxt('_build/{}_{}s_bearb.txt'.format(basename,time))
    H = np.abs(data[:,0])
    N = data[:,1]
    d_H = data[:,2]
    d_N = data[:,3]

    m_e = 9.1e-31
    c = 3e8
    e = 1.6e-19
    
    rate = N/time
    d_rate = d_N/time
    impuls = H * popt[0] + popt[1]
    d_impuls = np.sqrt((popt[0]*d_H)**2 + (H*pconv[0,0])**2 + (pconv[1,1])**2)
    energy = np.sqrt(1 + impuls**2)
    d_energy = impuls/energy*d_impuls

    print(basename)

    if basename == '04_Tl':
        xx = np.loadtxt('Daten/fermi_Tl.txt')
        converter = scipy.interpolate.interp1d(xx[:,0], xx[:,1], kind=1)
        F = converter(impuls)

        pl.clf()
        pl.plot(impuls, F)
        pl.plot(xx[:,0], xx[:,1], linestyle='None', marker='+')
        pl.savefig('Tl.pdf')

    else:
        pl.clf()
        xx = np.loadtxt('Daten/fermi_Na.txt')
        converter = scipy.interpolate.interp1d(xx[:,0], xx[:,1], kind=1)
        print(xx[:, 0])
        print(energy)
        F = converter(energy)

        x = np.linspace(np.min(xx[:, 0]), np.max(xx[:, 0]))
        y = converter(x)
        pl.plot(x, y)


        pl.plot(energy, F)
        pl.plot(xx[:,0], xx[:,1], linestyle='None', marker='+')
        pl.savefig('Na.pdf')


    K = np.sqrt(rate/(F*impuls*energy))

    T['Kurie_{}'.format(basename)] = list(zip(
        unitprint.siunitx(energy, d_energy),
        unitprint.siunitx(K)))

    np.savetxt('_build/Kurie_{}.txt'.format(basename), np.column_stack([energy, K, d_energy]))

    if basename == '04_Tl':
        popt, pconv = op.curve_fit(linear, energy[2:-1], K[2:-1])
    else:
        popt, pconv = op.curve_fit(linear, energy[5:-1], K[5:-1])
    
    E_max = -popt[1]/popt[0]
    dE_max = np.sqrt((pconv[1][1]/popt[0])**2 + (popt[1]*pconv[0][0]/popt[0]**2)**2)

    T['epsilon_max_{}'.format(basename)] = unitprint.siunitx(E_max, dE_max)

    x = np.linspace(np.min(energy), E_max, 10)
    y = linear(x,*popt)

    E_max *= m_e*c**2/e/1e3
    dE_max *= m_e*c**2/e/1e3
    T['E_max_{}'.format(basename)] = unitprint.siunitx(E_max, dE_max)

    fit_table = np.column_stack([x, y])
    np.savetxt('_build/fit_kurie_{}.txt'.format(basename), fit_table)


def fermi(filename):
    data = np.loadtxt('Daten/{}'.format(filename))
    x = data[:,0]
    F = data[:,1]

    popt, pconv = op.curve_fit(exp_sec_deg, x, F)

    return popt, pconv


def hall_offset(T):
    '''
    Berechnet den Hall Offset und gibt eine Umrechnungsfunktion zurück.

    :param dict T: Globales Template dice
    :return: Umrechnungsfunktion
    :rtype: function
    '''
    data = np.loadtxt('Daten/Remanenz.txt')
    rem_unten = data[:,0]
    rem_oben = data[:,1]
    rem_mittel = rem_oben-rem_unten
    offset = np.mean(rem_mittel)
    d_offset = np.std(rem_mittel)

    T['tab_remanenz'] = list(zip(
        unitprint.siunitx(rem_unten),
        unitprint.siunitx(rem_oben)
        ))

    T['hall_offset'] = unitprint.siunitx(offset, d_offset)

    def umrechner(skalen, fehler):
        '''
        Rechnet Skalenwerte in Skalenwerte ohne Offset um.

        :param float skalen: Skalenteile mit Offset
        :param float fehler: Fehler in Skalenteilen
        :return: Wert und Fehler
        :rtype: tuple
        '''
        neu_wert = skalen - offset
        neu_fehler = np.sqrt(fehler**2 + d_offset**2)

        return neu_wert, neu_fehler

    return umrechner

def spektrum_edit(T, basename, templatename, umrechner):
    data = np.loadtxt('Daten/{}.txt'.format(basename))

    untergrund = data[0,1]

    if templatename == 'Tl_80s':
        d_untergrund = 20
    else:
        d_untergrund = np.sqrt(untergrund)

    hall = data[1:,0]
    d_hall = np.ones(hall.shape) * 0.3

    ereignisse = data[1:,1]
    d_ereignisse = np.sqrt(ereignisse)

    T['{}_mess'.format(templatename)] = list(zip(
        unitprint.siunitx(hall, d_hall),
        unitprint.siunitx(ereignisse, d_ereignisse)
        ))

    T['{}_untergrund'.format(templatename)] = unitprint.siunitx(untergrund, d_untergrund)

    ereignisse = np.maximum(ereignisse-untergrund,0)
    d_ereignisse = np.sqrt(ereignisse + d_untergrund**2)

    hall, d_hall = umrechner(hall, d_hall)

    ereignisse /= np.abs(hall)
    d_ereignisse = np.sqrt((d_ereignisse/hall)**2+(ereignisse*d_hall/hall**2)**2)
    tabelle = np.column_stack([hall, ereignisse, d_hall, d_ereignisse])
    np.savetxt('_build/{}_bearb.txt'.format(basename), tabelle)

    T[templatename] = list(zip(
        unitprint.siunitx(hall, d_hall),
        unitprint.siunitx(ereignisse, d_ereignisse)
        ))


def main():
    T = {}

    umrechner = hall_offset(T)
    spektrum_edit(T, '01_Cs_40s', 'Cs_40s_kompl', umrechner)
    spektrum_edit(T, '02_Cs_40s', 'Cs_40s_ausschn', umrechner)
    spektrum_edit(T, '03_Cs_100s', 'Cs_100s', umrechner)
    spektrum_edit(T, '04_Tl_80s', 'Tl_80s', umrechner)
    spektrum_edit(T, '05_Na_200s', 'Na_200s', umrechner)
    impulseichung(T)

    dash_keys = []
    for key in T:
        if '-' in key:
            dash_keys.append(key)

    if len(dash_keys) > 0:
        print()
        print('**************************************************************')
        print('* Es dürfen keine Bindestriche in den Schlüsseln für T sein! *')
        print('**************************************************************')
        print()
        print('Folgende Schlüssel enthalten Bindestriche:')
        for dash_key in dash_keys:
            print('-', dash_key)
        print()
        sys.exit(100)

    with open('_build/template.js', 'w') as f:
        json.dump(dict(T), f, indent=4, sort_keys=True)

if __name__ == "__main__":
    main()
